parameters:
#    pm_workspace.example.class: PM\WorkspaceBundle\Example

services:
#    pm_workspace.example:
#        class: %pm_workspace.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
