security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main: 
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /admin/workspaces
            anonymous: true
            logout:
                path:   fos_user_security_logout
                target: /login
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/user, role: ROLE_ADMIN }
        - { path: ^/admin/roles, role: ROLE_ADMIN }
        - { path: ^/admin/status, role: ROLE_ADMIN }
        - { path: ^/admin/workflows, role: ROLE_ADMIN }
        - { path: ^/admin, role: IS_AUTHENTICATED_REMEMBERED }