pm_workspace_add:
    pattern:  /add
    defaults: { _controller: PMWorkspaceBundle:Workspace:add }
   
pm_workspace_todo:
    pattern: /{id}/todo
    defaults: { _controller: PMWorkspaceBundle:Task:todo }
    requirements:
        id:: \d+
        
pm_workspace_show:
    pattern: /{id}
    defaults: { _controller: PMWorkspaceBundle:Workspace:show }
    requirements:
        id:: \d+
    
pm_workspace_home:
    pattern:  /
    defaults: { _controller: PMWorkspaceBundle:Workspace:index }