<?php

namespace PM\WorkspaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusRepository extends EntityRepository
{
    public function findDefaultStatus($differentFrom = null)
    {
        
        $qb = $this->createQueryBuilder('s')
                ->where('s.defaultValue = 1');
        if(!is_null($differentFrom)){
            $qb = $qb->andWhere('s != :status')
                    ->setParameter('status', $differentFrom);
        }
                
        return $qb->getQuery()->getResult();
    }
}
