<?php

namespace PM\WorkspaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TodoHiddenStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoHiddenStatusRepository extends EntityRepository
{
}
