<?php

namespace PM\WorkspaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRoleWorkspaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRoleWorkspaceRepository extends EntityRepository
{
    
}
